### ISSUE TITLE
新建帖子后，如何更新网站？

### ISSUE THREAD

**Issue by luckypoem** [lizheming/PMBlog#1]
hi.

as3:~/PMBlog/html# cd post
as3:~/PMBlog/html/post# ls
hello-world.html
as3:~/PMBlog/html/post# nano test1.html
as3:~/PMBlog/html/post#

新建帖子后，如何更新网站？不知更新网站的命令是啥？
http://as3.brite.biz:1122,
http://as3.brite.biz:1122/post/test1.html(这个有点不正常吧？）

**Comment by lizheming** [comment]
文章存储应该是在md文件夹，html文件夹是最后程序生成的网站的。你想要更新的话直接访问index.php就行了，命令行的话就php index.php，不过还是推荐浏览器访问就是～

**Comment by luckypoem** [comment]
hi.
as3:~/PMBlog# ls
config.php  html  index.php  lib  md  ReadMe.md  tmp  version.json
as3:~/PMBlog# php index.php
PHP Fatal error:  Class 'Twig_Loader_Filesystem' not found in /root/PMBlog/index.php on line 250

怎么回事？如何解决？

**Comment by lizheming** [comment]
这是一个bug应该，你把 lib/Twig/loader 重命名成 lib/Twig/Loader 
就是把小写的loader改成大写的Loader应该就没有问题了
这个我会再下个版本中修复，感谢！

**Comment by luckypoem** [comment]
hi.
不行啊。改了也没用。怎么办？

as3:~/PMBlog/lib/Twig# ls
Autoloader.php             Lexer.php                 SimpleFilter.php
CompilerInterface.php      loader                    SimpleFunction.php
Compiler.php               LoaderInterface.php       SimpleTest.php
Environment.php            Markup.php                TemplateInterface.php
Error                      Node                      Template.php
Error.php                  NodeInterface.php         Test
ExistsLoaderInterface.php  NodeOutputInterface.php   Test.php
ExpressionParser.php       Node.php                  TokenParser
Extension                  NodeTraverser.php         TokenParserInterface.php
ExtensionInterface.php     NodeVisitor               TokenParser.php
Extension.php              NodeVisitorInterface.php  Token.php
Filter.php                 ParserInterface.php       TokenStream.php
Function.php               Parser.php
LexerInterface.php         Sandbox
as3:~/PMBlog/lib/Twig# mv loader Loader
as3:~/PMBlog/lib/Twig# ls
Autoloader.php             Lexer.php                 SimpleFilter.php
CompilerInterface.php      Loader                    SimpleFunction.php
Compiler.php               LoaderInterface.php       SimpleTest.php
Environment.php            Markup.php                TemplateInterface.php
Error                      Node                      Template.php
Error.php                  NodeInterface.php         Test
ExistsLoaderInterface.php  NodeOutputInterface.php   Test.php
ExpressionParser.php       Node.php                  TokenParser
Extension                  NodeTraverser.php         TokenParserInterface.php
ExtensionInterface.php     NodeVisitor               TokenParser.php
Extension.php              NodeVisitorInterface.php  Token.php
Filter.php                 ParserInterface.php       TokenStream.php
Function.php               Parser.php
LexerInterface.php         Sandbox
as3:~/PMBlog/lib/Twig# cd ~/PMBlog/
as3:~/PMBlog# ls
config.php  html  index.php  lib  md  ReadMe.md  tmp  version.json
as3:~/PMBlog# php index.php
PHP Fatal error:  Class 'Twig_Loader_Filesystem' not found in /root/PMBlog/index.php on line 250
as3:~/PMBlog#

**Comment by lizheming** [comment]
对不起，我没发现filesystem.php这个文件的名称也不对
请再把 lib/Twig/Loader/filesystem.php 修改成 lib/Twig/Loader/Filesystem.php
这都是遗留的错误，本来应该已经解决了的，可能我上次回退了版本又忘记了这个事了，对不起！

**Comment by luckypoem** [comment]
何来对不起？谢谢你的程序。问题解决！

**Comment by lizheming** [comment]
分享出来的代码就应该让人舒舒爽爽的用不是么，还没运行成功一次就各种碰壁，使用者的心情肯定是不爽的，这属于作者的过失，说声对不起是应该的。

**Comment by luckypoem** [comment]
hi.
此文http://imnerd.org/lab/pmblog-doc.html说：
"程序支持非全文输出，即部分输出。在撰写文章时，在想要输出的文字后面添加程序将在首页不输出其之后的文字，并添加一个全文链接"，我试过了，我编辑此文http://pmb.brite.biz//post/chinese-economy.html，添加，然后用php index.php更新网站，完全没效果。怎么回事？

**Comment by lizheming** [comment]
额，升级新版换了模板引擎之后好像还没来得及加上，我下个版本争取支持！

**Comment by lizheming** [comment]
你好，新增了`post.opening`和`post.read_more`两个变量，前者用于输出摘要，后者用于判断摘要是否为全文，更多接口变量请看[数据类型及字段](https://github.com/lizheming/PMBlog/wiki/%E6%95%B0%E6%8D%AE%E7%B1%BB%E5%9E%8B%E5%8F%8A%E5%AD%97%E6%AE%B5)

如果你想要在首页显示摘要的话，则需要将主题中的`{{post.content}}`替换为`{{post.opening}}`

当输出部分全文的时候你可能还需要显示一个`阅读更多`按钮，那么你需要添加如下代码

```
{% if post.read_more %}
    <a href="{{post.url}}" title="{{post.title}}">阅读更多</a>
{% endif %}
```

**Comment by luckypoem** [comment]
hi.
好久没来了，你更新源码了吗？可否把对应于我的网站http://pmb.brite.biz/ 的源码（旧源码）上传到某个branch呢？

**Comment by lizheming** [comment]
@luckypoem 嗯，为什么需要老代码呢？你需要哪个版本的代码？代码更新了好多我也没有再本地管理老代码，或许你可以看看commit？
