### ISSUE TITLE
Editor插件转义双引号

### ISSUE THREAD

**Issue by lizheming** [lizheming/PMBlog#3]
@perichr 插件会转义双引号导致一些Markdown语法中的引号也被转义从而不能正常工作，建议修正或去除。
另外希望能修改一下预览样式，可参考MarkdonPad 1的默认样式。

**Comment by lizheming** [comment]
另外编辑器的弹出框的背景没有了，希望修复一下。

**Comment by perichr** [comment]
除了引号转义，算是……修复了？

**Comment by lizheming** [comment]
@perichr 好的，我先试试看。

**Comment by lizheming** [comment]
@perichr 背景和预览问题已修复，剩下的转义问题我也不清楚了，刚才看了下POST提交的过程一样没问题。

**Comment by lizheming** [comment]
我把插件重写了，转义的问题似乎没有了。
