### ISSUE TITLE
安装有错误啊。

### ISSUE THREAD

**Issue by hsmw** [lizheming/PMBlog#7]
Parse error: syntax error, unexpected T_FUNCTION, expecting ')' in D:\APMServ5.2.6\www\htdocs\pmblog\admin\var\parse.php on line 603

**Comment by hsmw** [comment]
PHP 环境 5.2.6  APMServ5.2.6 架构

**Comment by lizheming** [comment]
@hsmw 额，用了一个匿名函数没注意到，把PHP版升级下（5.3应该就可以了）可以解决这个问题，下个版本我会改回来的，谢谢你的反馈。

**Comment by hsmw** [comment]
有没有群，或者联Q。可以交流的？

**Comment by lizheming** [comment]
@hsmw 额暂时没有群，可以加我Q联系 secret_lzm_007#qq.com
