### ISSUE TITLE
怎么写文章呢？

### ISSUE THREAD

**Issue by xaero7** [lizheming/PMBlog#9]
如何写文章呢？地址是啥？

**Comment by lizheming** [comment]
markdown 文件写好之后直接放到 `/usr/contents` 里面，访问 `url.com/admin/index.php` 更新文章。
或者下载 [Editor](https://github.com/lizheming/PMBlog/tree/plugins/Editor) 这个插件放到 `/usr/plugins` 里面，访问 `url.com/admin/index.php?new` 开启编辑器页面。
